#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  6             \
    bottom_padding               6             \
    left_padding                 6             \
    right_padding                6             \
    window_gap                   6             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    window_opacity               off            

#ignore apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Charles$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^DBeaver.*$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Tunnelblick$" manage=off
yabai -m rule --add app="^Insomnium$" manage=off
yabai -m rule --add app="^Insomnia$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off

echo "yabai configuration loaded.."

